### ISSUE TITLE
Test Script Not Working

### ISSUE THREAD

**Issue by Rebem13** [tronikos/google_assistant_sdk_custom#1]
I'm using your (fantastic) custom integration to ask my Volvo EV how much fuel (battery) it has through Google Assistant. The install went ok I think and I've duplicated your automations and a script to emulate what I want to achieve. When I run my script (below), I get a prompt on my mobile phone to "Set up voice match". I've done all the setup I can on Google Assistant on the phone by following the prompt. I'm fresh out of ideas. Any suggestions please?

volvo_battery_refresh:
  alias: 'Volvo Battery : Refresh'
  sequence:
  - service: google_assistant_sdk.send_text_command
    data:
      command: how much fuel does my car have
  mode: single
  icon: mdi:car

**Comment by tronikos** [comment]
What do you get at https://myactivity.google.com/myactivity when you issue the command?

**Comment by stevelup** [comment]
Hi

I have the same scenario - I get prompted to set up Voice Match, but it's already set up, so there's nothing further I can do.

Here's the output from My Activity.

Said [is my car charging]
For that, I'll need to verify your identity through voice match.
To set it up, follow the steps I've sent to your phone.
Our last update from Polestar was 2 hr ago. At that point your vehicle was plugged in but not charging.

Weirdly, the answer is actually there, but doesn't make it back to Home Assistant.

Here's the debug output from HASS.

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/google_assistant_sdk/helpers2.py:15
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 17:42:51 (1 occurrences)
Last logged: 17:42:51

[139752795201760] Error handling message: Unknown error (unknown_error) Steve Lupton from fe80::8497:15a:82b9:d078 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/conversation/__init__.py", line 164, in websocket_process
    result = await async_converse(
  File "/usr/src/homeassistant/homeassistant/components/conversation/__init__.py", line 288, in async_converse
    result = await agent.async_process(
  File "/usr/src/homeassistant/homeassistant/components/google_assistant_sdk/__init__.py", line 174, in async_process
    text_response = parse_response(self.hass, user_input.text, resp)
  File "/usr/src/homeassistant/homeassistant/components/google_assistant_sdk/helpers2.py", line 15, in parse_response
    html = BeautifulSoup(resp[1], "html.parser")
  File "/usr/local/lib/python3.10/site-packages/bs4/__init__.py", line 313, in __init__
    elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()`

**Comment by Rebem13** [comment]
> What do you get at https://myactivity.google.com/myactivity when you issue the command?

Same error as @stevelup in my activity log.

**Comment by tronikos** [comment]
Maybe it would work if you enable personal results? You would have to manually apply changes in https://github.com/home-assistant/core/pull/88871 and follow instructions in https://github.com/home-assistant/home-assistant.io/pull/26390

It might be easier to experiment with the underlying library at https://github.com/tronikos/gassist_text by running the included demo.py

**Comment by tronikos** [comment]
The latest release v0.0.4, which requires 2023.7, enables personal results. Can you try the command again?

**Comment by stevelup** [comment]
Hi

I'm struggling to get personal results working. Home Assistant is on 2023.7.1 and your custom integration has been reinstalled - v0.0.6 - but I'm still getting the same thing.

```
For that, I'll need to verify your identity through voice match.
To set it up, follow the steps I've sent to your phone.
```

I can't actually find the debug logging for the integration any more either - not sure what I'm doing wrong...

**Comment by tronikos** [comment]
Does "what is my name?" work? If it does and you still get the same error then enabling personal results won't help for car queries.

**Comment by stevelup** [comment]
Yes, sorry I wasn't clear. That is the response to 'what is my name'.

I'll spend some more time on it tomorrow.

**Comment by joskfg** [comment]
The notification in the mobile doesn't open any applicaiton, it just show a quick black screen and nothing more. Using a OnePlus 9 pro.

**Comment by tronikos** [comment]
Added a note in the underlying library "Commands that need to verify your identity through voice match don't work"
