### ISSUE TITLE
Failed to apply patch :( since 2023.9

### ISSUE THREAD

**Issue by collateral87** [tronikos/google_assistant_sdk_custom#10]
![Screenshot_20230906_233949_Home Assistant.jpg](https://github.com/tronikos/google_assistant_sdk_custom/assets/97076257/cb553b29-d3f5-45a9-b1c1-f92ffefa8ab8)

It seems like there is an incompatible issue in homeassistant 2023.9.
Installation method is HAOS

**Comment by tronikos** [comment]
Fixed in v0.0.7
