### ISSUE TITLE
There are still cases in which the response is not valid.

### ISSUE THREAD

**Issue by StefanoGiu** [tronikos/google_assistant_sdk_custom#11]
I think the main issue of Google Assistant SDK is that the integration is invoking the Google APIs for a Smart Display device and not for a device like a Smart Speaker with no display...

I tried to get the HTML as output from the assist response, and it has the standard low bar darker area, with the reply and the buttons you can press on a Smart Display... with the Google Assistant Logo... and sometimes, the answer is "Here it is what I found on the web..." This is actually not an answer...

I think you should try to change the API to invoke it as a Smart Speaker instead of Smart Display... this would make the trick...

Thank you

**Comment by StefanoGiu** [comment]
I found the problem. In init file you should change from:
self.assistant = TextAssistant(credentials, self.language, display=True)
to
self.assistant = TextAssistant(credentials, self.language, display=False)

This is fixing the issue!!!

**Comment by tronikos** [comment]
What's your query? The purpose of this custom integration is mostly to get responses for home control commands. E.g. if you ask "what's the status of X" with display=False you won't get a text response, see https://github.com/googlesamples/assistant-sdk-python/issues/391 The workaround is to set display=True and parse the HTML response.

**Comment by StefanoGiu** [comment]
I'm using this integration with a vocal speaker I made, connected with HA...

I'm going to patch the integration using False as default, then if I get None, I will interrogate it again with True.

**Comment by tronikos** [comment]
Commands like "brighten the lights" or "toggle the lights" will be executed twice and will have undesired effect. I'm closing this since having display=True is intended. It's the workaround to get responses for home control commands.
