### ISSUE TITLE
Event not triggering and response text is null

### ISSUE THREAD

**Issue by Sloy** [tronikos/google_assistant_sdk_custom#12]
Hi! I'm trying to figure out how to use this patch to do something similar to https://github.com/tronikos/google_assistant_sdk_custom/issues/3.

I updated Home Assistant to the latest version (2023.10.3) and installed this patch (v0.0.7). I did not setup personal results (that's not needed for general commands, right?). 

To test the integration I'm sending commands through Developer Tools invoking the Google Assistant service like this:
```
service: google_assistant_sdk.send_text_command
data:
  command: is the AC turned on
```

I suppose I should be able to see an event called `google_assistant_sdk_custom_event`. When I listen for such event in the Developer Tools I don't see any trigger (neither in my automation). However I can see the commands in https://myactivity.google.com/myactivity?product=31 with the expected text response.

Another stange thing I also see is that the service response contains null text. I don't fully understand yet how service responses work, but I guess I should be seeing the text response in here, right?
```
responses:
  - text: null
```

Am I missing something? I'd like to know how to debug the issue, but I'm not sure how. I tried looking the debug logs from Google Assistant SDK integration and all I see related to this is the following:
```
2023-10-22 13:13:36.155 DEBUG (MainThread) [homeassistant.components.google_assistant_sdk.helpers] command: is the AC turned on
response: None
```
I would appreciate some help figuring out how to proceed. Thanks for your time!

**Comment by tronikos** [comment]
Can you try the latest release and calling `google_assistant_sdk_custom.send_text_command`?

**Comment by Sloy** [comment]
Awesome! I tried the 0.1.0 version and it works fine. I think your new approach is a good idea. Thanks for the fix and for the feature :)
