### ISSUE TITLE
Error setting up entry Google Assistant SDK Custom for google_assistant_sdk_custom

### ISSUE THREAD

**Issue by backslashV** [tronikos/google_assistant_sdk_custom#17]
```
Error setting up entry Google Assistant SDK Custom for google_assistant_sdk_custom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/google_assistant_sdk_custom/__init__.py", line 66, in async_setup_entry
    implementation = await async_get_config_entry_implementation(hass, entry)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 402, in async_get_config_entry_implementation
    implementation = implementations.get(config_entry.data["auth_implementation"])
                                         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'auth_implementation'
```
I deleted the integration before updating as instructed. Now, I am getting the above error in the logs and this
The automation xyz has an action that calls an unknown service: `google_assistant_sdk_custom.send_text_command`

**Comment by tronikos** [comment]
Do you have the official Google Assistant SDK? Does that work? You can have both at the same time. Which installation method of Home Assistant do you have?

**Comment by backslashV** [comment]
> Do you have the official Google Assistant SDK? Does that work? You can have both at the same time. Which installation method of Home Assistant do you have?

Yes, the official one is working fine, and I am using both at the same time. I'm on Home Assistant OS.

**Comment by backslashV** [comment]
Oh I am seeing just the official "Assistant SDK" credentials there. I followed the instructions for generating credentials for the custom version and put the file in the /config folder. It seems the integration isn't picking it even after a reboot.

**Comment by tronikos** [comment]
You need to first configure the application credentials. Try renaming the file in the /config folder, and then remove and re-add this custom integration. It should ask you to authenticate. Once done confirm you have two applications credentials, one for the official, one for the custom. Finally you can rename back the file in the /config folder to allow personal results.

**Comment by backslashV** [comment]
Thanks. When I tried to authenticate, I got this error:
```
You can’t sign in because this app sent an invalid request. You can try again later, or contact the developer about this issue.
If you are a developer of this app, see [error details](https://accounts.google.com/).
Error 400: redirect_uri_mismatch
```

**Comment by tronikos** [comment]
First make a backup. Then try editing `/config/.storage/core.config_entries` and copy all the data section from `google_assistant_sdk` to `google_assistant_sdk_custom` changing `google_assistant_sdk` to `google_assistant_sdk_custom` in `auth_implementation`. Then restart. If it works add back the `google_assistant_sdk_credentials.json` and restart.

**Comment by backslashV** [comment]
I seem to have fixed it. Originally, I was following the instructions on the GitHub page and created an OAuth client with application type of "Desktop app". I was reusing this one for authenticating the integration as opposed to creating a separate "Web app" one. Apologies for taking your time.
