### ISSUE TITLE
Unable to set device name

### ISSUE THREAD

**Issue by amosyuen** [tronikos/google_assistant_sdk_custom#18]
Tried following https://github.com/tronikos/google_assistant_sdk_custom#enable-personal-results. At the step where I tap the notification, the screen quickly flashes as if opening another app, but ends up just displaying my home screen so I am unable to set a device name.

Tried restarting the phone, but that didn't help. Tried opening the assistant app and going into settings for personal results but don't see any new device there.

**Comment by tronikos** [comment]
I wonder if it depends on the OS version or Home app version. I did it on Android a while ago. Not sure what version. If you have access to a different phone or tablet or even iOS it might be worth trying that. You could even try on an emulator trying different versions for both the OS and the Home app.

**Comment by tronikos** [comment]
Can you try the instructions at `https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Setup-Authentication-for-Google-Assistant-Unofficial-Desktop-Client#enabling-personal-results-optional` and more importantly `https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/issues/784#issuecomment-1315526397`?

**Comment by tronikos** [comment]
A comment in the linked bug says: "However, I was able to resolve the issue by using an Android emulator to receive the notification on an Android 12 device, instead of my current Android 9 device"

What version are you running?

**Comment by amosyuen** [comment]
I have Pixel 6 on Android 14. Using an emulator with android 5.6 worked for me.

**Comment by tronikos** [comment]
Updated README suggesting users to use an emulator.

**Comment by ejpenney** [comment]
I'll add here for future Googlers, Android Studio's V12 emulator does not work, nor does the V11: These just flash the screen and don't provide the dialog. After reading [this](https://github.com/tronikos/google_assistant_sdk_custom/issues/8#issuecomment-1645253662) I downgraded all the way to the 7.1.1 emulator, updated Play Services, and installed Assistant and it finally worked.  5.6 is now too old for Android Studio, there may be a newer one that works, but it appears the older the better!

**Comment by tronikos** [comment]
Could you please update the documentation at https://www.home-assistant.io/integrations/google_assistant_sdk/#enable-personal-results-for-advanced-users ?
