### ISSUE TITLE
Web Scraping?

### ISSUE THREAD

**Issue by higbyk** [tronikos/google_assistant_sdk_custom#20]
Not really an issue but I don't see why this can't be included in the main integration. Your rationale is that parsing HTML is not allowed, but that is explicitly listed as an exception to the web scraping rule, on the page you linked:
![Screenshot_20240129-205847.png](https://github.com/tronikos/google_assistant_sdk_custom/assets/17530451/e611b520-b435-4914-8f61-0f622d91a844)

So it seems there is no reason for this not to be included in the Google Assistant SDK integration. Did you submit a pull request and have it denied?

**Comment by tronikos** [comment]
See https://github.com/home-assistant/core/pull/85782
