### ISSUE TITLE
Access blocked: This app’s request is invalid

### ISSUE THREAD

**Issue by Developer-Huw** [tronikos/google_assistant_sdk_custom#21]
When I go to enable the intergration in Devices & Services > Add Intergration > Google Assistant SDK Custom It takes we to a website where it says:

Access blocked: This app’s request is invalid

<my-email>
You can’t sign in because this app sent an invalid request. You can try again later, or contact the developer about this issue. [Learn more about this error](https://developers.google.com/identity/protocols/oauth2/web-server#authorization-errors-redirect-uri-mismatch)
If you are a developer of this app, see [error details](https://accounts.google.com/).
Error 400: redirect_uri_mismatch

Any help is good

**Comment by tronikos** [comment]
Remove the relevant credentials from http://homeassistant.local:8123/config/application_credentials and follow the instructions again

**Comment by DevHuw** [comment]
Where do I find them?

**Comment by tronikos** [comment]
Using the URL I provided, or go to settings > devices & services > 3 dots up right corner > application credentials

**Comment by Developer-Huw** [comment]
Ahh amazing tysm!

**Comment by Developer-Huw** [comment]
Are you able to manage timers @tronikos ?

**Comment by tronikos** [comment]
No timers aren't supported

**Comment by Developer-Huw** [comment]
Okay is that an API thing or smt else

**Comment by tronikos** [comment]
I think https://github.com/leikoilja/ha-google-home supports timers
