### ISSUE TITLE
Stuck, can't edit incorrect config

### ISSUE THREAD

**Issue by jtenniswood** [tronikos/google_assistant_sdk_custom#22]
I can't figure out how to update an incorrect setup, as I can't reopen the dialogue box, and am unable to authorize the connection.
Could you add some option to edit it (or tell me where the setting is), as I've tried uninstalling and reinstalling but the config remains set.
Thanks

**Comment by tronikos** [comment]
See https://www.home-assistant.io/integrations/google_assistant_sdk/#troubleshooting

"If you have an error with your credentials you can delete them in the [Application Credentials](https://www.home-assistant.io/integrations/application_credentials/) user interface."
