### ISSUE TITLE
Re-authentication almost everyday

### ISSUE THREAD

**Issue by nicolas-meunier-97** [tronikos/google_assistant_sdk_custom#23]
Hi! First of all thank you for this project !
I have a problem where this integration disconnect almost every day, and necessitate a re-authentication to my Google account. Is it just a normal thing with Google or a bug with the integration?
Thanks!

**Comment by tronikos** [comment]
Follow steps at https://www.home-assistant.io/integrations/google_assistant_sdk/ and the attached video again. Most likely you missed step: "Select OAuth consent screen again and under Publishing status, select Publish app. Otherwise your credentials will expire every 7 days."

**Comment by nicolas-meunier-97** [comment]
Thank you so much! I missed that step it seems 😅
