### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Fernando-Checa** [tronikos/google_assistant_sdk_custom#27]
Hello,
I'm on HA 2024.10.3 and when I try to set up the integration, I get a pop up telling me that I need to open a website, which gives an error..
The form where you input client ID and secret does not appear.
I tried deleting and reinstalling but no luck.

![CleanShot 2024-10-25 at 21 31 45](https://github.com/user-attachments/assets/e1d6ffdc-16b7-481c-be44-d37f0f9efa5b)

![CleanShot 2024-10-25 at 21 32 11](https://github.com/user-attachments/assets/dfc5790d-be5e-4b69-831a-46b4f2fba5be)

**Comment by tronikos** [comment]
Follow the instructions at https://www.home-assistant.io/integrations/google_assistant_sdk/ 
Make sure you actually follow step 14:

Add https://my.home-assistant.io/redirect/oauth to Authorized redirect URIs then select Create.
This is not a placeholder. It is the URI that must be used.
