### ISSUE TITLE
Tell a joke not working 

### ISSUE THREAD

**Issue by sammers101** [tronikos/google_assistant_sdk_custom#28]
This does nothing except sometimes will make a chime sound:

action:
  - action: google_assistant_sdk.send_text_command
    data:
      command: Tell me a joke
      media_player: media_player.googlenestpointa56d_2
    enabled: true
  - action: google_assistant_sdk.send_text_command
    metadata: {}
    data:
      command: Tell me a joke on the kitchen speaker
    enabled: true
mode: single

Yet this works fine for me:
- action: google_assistant_sdk.send_text_command
    metadata: {}
    data:
      command: Turn off kitchen light
mode: single

**Comment by tronikos** [comment]
https://www.home-assistant.io/integrations/google_assistant_sdk/#limitationsknown-issues
