### ISSUE TITLE
Failed to apply patch :(   since ha 2023.7

### ISSUE THREAD

**Issue by collateral87** [tronikos/google_assistant_sdk_custom#5]
![Screenshot_20230706_002252_Home Assistant](https://github.com/tronikos/google_assistant_sdk_custom/assets/97076257/55abc5bf-fcd6-4d26-8b52-1bd19f0416b3)

It seems like there is an incompatible issue in homeassistant 2023.7.
Installation method is HAOS

**Comment by tronikos** [comment]
Can you try the latest v0.0.4 release? As a bonus this release enables personal results. See documentation.

**Comment by tronikos** [comment]
Make that v0.0.5 since there was a bug in v0.0.4. Please reopen if this didn't fix it.

**Comment by collateral87** [comment]
The error is back in 2023.9.
