### ISSUE TITLE
Specific device actions

### ISSUE THREAD

**Issue by TheFes** [tronikos/google_assistant_sdk_custom#7]
Would it somehow be possible to also have device specific commands, like setting an alarm on the bedroom hub, or initiating a duo call to grandma on the living room nest mini?

**Comment by tronikos** [comment]
I don't think this is possible. It seems you can only perform these commands on the device itself, not from a separate device. E.g. I cannot perform the actions you described from the mobile version of Google Assistant so for sure they aren't supported from the Google Assistant API that supports a subset of the mobile version.
